# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: OpenCDSS
pages:
- Introduction: index.md
- OpenCDSS Licensing: licensing.md
- OpenCDSS Version Control: version-control.md
- OpenCDSS Documentation: documentation.md
- OpenCDSS Development Environment: dev-env.md
- OpenCDSS Testing: testing.md
- OpenCDSS Workflow: workflow.md
- StateCU: statecu/statecu.md
- StateCU-GUI: statecu-gui/statecu-gui.md
- StateDMI: statedmi/statedmi.md
- StateMod: statemod/statemod.md
- StateMod GUI: statemod-gui/statemod-gui.md
- StateView: stateview/stateview.md
- TSTool: tstool/tstool.md
#- Resources: resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/cdss-website-opencdss
site_description:  OpenCDSS
site_author:  Open Water Foundation
site_favicon:  'images/opencdss-favicon.ico'
copyright:  State of Colorado, Department of Natural Resources
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
