# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: OpenCDSS
nav:
- Introduction: index.md
- OpenCDSS Licensing: licensing.md
- OpenCDSS Version Control: version-control.md
- OpenCDSS Documentation: documentation.md
- OpenCDSS Development Environment: dev-env.md
- OpenCDSS Testing: testing.md
- OpenCDSS Workflow: workflow.md
- HydroBase: hydrobase.md
- StateCU: statecu.md
- StateCU GUI: statecu-gui.md
- StateDMI: statedmi.md
- StateMod: statemod.md
- StateMod GUI: statemod-gui.md
- StateView: stateview.md
- TSTool: tstool.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  State of Colorado, Department of Natural Resources
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
 - 'UA-43023264-1'
 - auto
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/cdss-website-opencdss
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  OpenCDSS
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon:  'images/NewCOLogo32x32.gif'
